### ISSUE TITLE
Is the file cssParser.js missing?

### ISSUE THREAD

**Issue by astridx** [carlsonsantana/HaTeMiLe-for-JavaScript#11]
Thank you for hatemile-for-javascript.
I miss the file `/path/to/js/cssParser.js"`.

**Comment by carlsonsantana** [comment]
This file is provided by the external library JSCSSP, available on http://sources.disruptive-innovations.com/jscssp/trunk/cssParser.js.

**Comment by astridx** [comment]
Thank you.
